### ISSUE TITLE
Лох

### ISSUE THREAD

**Issue by 0BlueSnake0** [trev-git/lectures#1]
Запятую не поставил, попуск.

**Comment by Mursulov** [comment]
определенно

**Comment by trev-git** [comment]
и чё

**Comment by Mursulov** [comment]
ниче, запятую поставь
@

**Comment by 0BlueSnake0** [comment]
хуй в очко

**Comment by 0BlueSnake0** [comment]
катись к хуям, репозиторий говно

**Comment by 0BlueSnake0** [comment]
насрал в ветку и радуется

**Comment by 0BlueSnake0** [comment]
в мастер насрал

**Comment by 0BlueSnake0** [comment]
надеюсь работодатель не увидит, куда и какие issue я писал

**Comment by trev-git** [comment]
катись к хуям и еби осла

**Comment by 0BlueSnake0** [comment]
ебать осла мы будем твоим репозиторием, потому что он длинный сука как член африканского козла. И бесполезный кстати тоже.

**Comment by Mursulov** [comment]
Блять вы заебали, поебитесь еще

**Comment by 0BlueSnake0** [comment]
кстати покажи этот репозиторий рекрутеру в гугл, он будет в восторге

**Comment by trev-git** [comment]
пошёл нахуй

**Comment by 0BlueSnake0** [comment]
нет.

**Comment by trev-git** [comment]
пидора ответ

**Comment by 0BlueSnake0** [comment]
.

**Comment by Mursulov** [comment]
Проверь свою мать

**Comment by 0BlueSnake0** [comment]
храни твой репозиторий ахахах

**Comment by 0BlueSnake0** [comment]
или удаляй его нахуй, чтобы так стыдно не было

**Comment by 0BlueSnake0** [comment]
удали мастер

**Comment by trev-git** [comment]
насрал в репу сука и радуется

**Comment by Mursulov** [comment]
![z3lGk7GkCwA.jpg](https://user-images.githubusercontent.com/78586711/214773833-a9677cae-7c59-49eb-b9d0-604b340f7c6e.jpg)

`

**Comment by 0BlueSnake0** [comment]
будешь хуй?

**Comment by trev-git** [comment]
![photo_2023-01-25_20-54-31](https://user-images.githubusercontent.com/29712146/214774136-50523b6c-e7ae-45cf-baea-384fbe0765a9.jpg)

**Comment by 0BlueSnake0** [comment]
бля давайте чатиться не через телеграм, а делать коммиты в файл drist_
chat.txt

**Comment by 0BlueSnake0** [comment]
dreeassssssssssssttttt

**Comment by 0BlueSnake0** [comment]
забей
все равно насрано как на Лубянке

**Comment by trev-git** [comment]
пиздец

**Comment by 0BlueSnake0** [comment]
насрано

**Comment by 0BlueSnake0** [comment]
ass

**Comment by 0BlueSnake0** [comment]
удаляй нахуй репозиторий короче, а то опозоримся коллективно

**Comment by trev-git** [comment]
cock

**Comment by 0BlueSnake0** [comment]
теперь твой репозиторий будет официально дрист-чатом мткп
